import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Graph from '../Components/Graph';
import { FormEvent, useEffect, useRef, useState } from 'react';
import SearchBar from '../Components/SearchBar';
import CurrencyToggle from '../Components/CurrencyToggle';

export default function Home() {

  //logo = a cube! with stocks on it!!!!!

  const [stocks, setStocks] = useState(null)
  const [currencies, setCurrencies] = useState(null)
  const [strCurrency, setStrCurrency] = useState("USD($)")
  const [conversion, setConversion] = useState(1)
  const searchForm = useRef([]);

  const getStocksData = async (company: string) => {
    try {
      const res = await fetch(`https://www.alphavantage.co/query?function=TIME_SERIES_INTRADAY&symbol=${company}&interval=60min&apikey=${process.env.NEXT_PUBLIC_STOCKAPI_ACCESS_KEY}`)
      const stocksData = await res.json();
      setStocks(stocksData)
    } catch (error) {
      console.log(error);

    }
  }

  const searchForStocks = (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault()
    const company: string = searchForm.current.value.toUpperCase();
    console.log(company);
    getStocksData(company);
    searchForm.current.value = "";
  }

  const getCurrencyAPI = async () => {
    const res = await fetch(`https://api.currencyapi.com/v3/latest?apikey=${process.env.NEXT_PUBLIC_CURRENCY_KEY}&currencies=EUR%2CUSD%2CCAD%2CGBP`)
    const currencyData = await res.json();
    setCurrencies(currencyData);
    console.log(currencies);    
  }

  //need to always calculate from usd to new currency

  useEffect(() => {
    getCurrencyAPI()
  }, [])

  const calculateConversion = (currency: string) => {
    switch (currency) {
      case "CAD($)":
        console.log(currency);
        console.log(currencies.data.CAD.value);
        setConversion(currencies.data.CAD.value) 
        setStrCurrency("CAD($)")      
        break;
      case "GBP(£)":
        console.log(currency);
        console.log(currencies.data.GBP.value); 
        setConversion(currencies.data.GBP.value) 
        setStrCurrency("GBP(£)")
        break;
      case "EUR(€)":
        console.log(currency);
        console.log(currencies.data.EUR.value); 
        setConversion(currencies.data.EUR.value)
        setStrCurrency("EUR(€)") 
        break;
      default:
        console.log(currency);
        console.log(currencies.data.USD.value); 
        setConversion(currencies.data.USD.value) 
        setStrCurrency("USD($)")
        break;
    }
  }



  return (
    <div className={styles.container}>
      <Head>
        <title>Stock Cube</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <SearchBar searchForStocks={searchForStocks} searchForm={searchForm} />
        <CurrencyToggle calculateConversion={calculateConversion} />
        {stocks && <Graph stocks={stocks} conversion={conversion} strCurrency={strCurrency}/>}
      </main>

      <footer className={styles.footer}>
        hi
      </footer>
    </div>
  )
}

