import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Graph from '../Components/Graph';
import { FormEvent, useEffect, useRef, useState } from 'react';
import SearchBar from '../Components/SearchBar';

export default function Home() {

  const [stocks, setStocks] = useState(null)
  const searchForm = useRef(null);

  const getStocksData = async (company: string) => {
    const res = await fetch(`https://www.alphavantage.co/query?function=TIME_SERIES_INTRADAY&symbol=${company}&interval=60min&apikey=${process.env.NEXT_PUBLIC_STOCKAPI_ACCESS_KEY}`)
    const stocksData = await res.json();
    setStocks(stocksData)    
  }

  const searchForStocks = (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault()
    const company: string = searchForm.current.value;
    console.log(company);
    getStocksData(company);
    searchForm.current.value = "";
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <SearchBar searchForStocks={searchForStocks} searchForm={searchForm}/>
        {stocks != null && <Graph stocks={stocks} />}
      </main>

      <footer className={styles.footer}>
        hi
      </footer>
    </div>
  )
}

